language: python

python:
  - "3.6.5"


install:
  - pip install -r requirements.txt
  - pip install coveralls

rvm:
  - 2.2.0

env:
    global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d
  DB_URL="postgres://postgres:tony1234@localhost/stackoverflowlite"
  DB_TEST_URL="postgres://postgres:tony1234@localhost/test_stackoverflowlite"
  FLASK_APP=run
  CONFIG=testing

script: 
  - py.test --cov=api
  - bundle exec rspec


services:
  - postgresql


before_script:
  - psql -c 'create database stackoverflowlite;' -U postgres
  - psql -c 'create database test_stackoverflowlite;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
- coveralls

addons:
  postgresql: "9.5"

